# Generated by Django 4.2.7 on 2023-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('summary', models.TextField()),
                ('wanted_job_title', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('edu_description', models.TextField()),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('header_color', models.CharField(max_length=7)),
                ('header_text_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='resumesettings',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ResumeSettings',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
