# Generated by Django 4.2.7 on 2023-11-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenerator', '0002_cvtemplate_remove_employment_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('edu_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_color', models.CharField(max_length=7)),
                ('header_text_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='edu_description',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='education_end_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='education_start_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='employment_start_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='header_color',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='header_text_color',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='project_end_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='qualification',
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='educations',
            field=models.ManyToManyField(blank=True, to='CVgenerator.education'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='employments',
            field=models.ManyToManyField(blank=True, to='CVgenerator.employment'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='projects',
            field=models.ManyToManyField(blank=True, to='CVgenerator.project'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='resume_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CVgenerator.resumesettings'),
        ),
    ]
