# Generated by Django 4.2.7 on 2023-12-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenerator', '0006_cvtemplate_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvtemplate',
            old_name='additional_info',
            new_name='type',
        ),
    ]
