# Generated by Django 4.2.7 on 2023-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenerator', '0007_rename_additional_info_cvtemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtemplate',
            name='type',
            field=models.TextField(),
        ),
    ]
